In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

In [3]:
train = pd.read_csv("../data/train.csv")

In [4]:
test = pd.read_csv("../data/test.csv")

In [4]:
train

,acqic,bacno,cano,conam,contp,csmcu,ecfg,etymd,flbmk,flg_3dsmk,...,iterm,locdt,loctm,mcc,mchno,ovrlt,scity,stocn,stscd,txkey
0,6881,113261,38038,513.80,5,0,N,0,N,N,...,0,33,172652.0,457,59333,N,0,102,0,516056
1,6881,15408,188328,513.80,5,0,N,0,N,N,...,0,6,152458.0,457,59333,N,0,102,0,483434
2,6716,157159,29967,1016.11,5,62,N,5,N,N,...,0,5,172946.0,247,50436,N,3281,102,0,1407164
3,5975,105985,81305,713.66,5,62,N,4,N,N,...,0,6,182129.0,263,93775,N,5817,102,0,1051004
4,6411,94435,49219,1806.49,3,62,N,4,N,N,...,0,6,172624.0,339,0,N,5865,102,0,1622153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141335,6032,2510,54094,1.38,5,75,Y,2,NaN,NaN,...,0,30,231435.0,248,78297,N,5817,102,0,196080
1141336,1801,12832,137381,1138.04,5,75,Y,8,NaN,NaN,...,0,1,100009.0,201,198,N,1852,98,0,642025
1141337,6322,91008,15189,578.38,5,75,Y,8,NaN,NaN,...,0,4,191642.0,209,38222,N,5817,102,0,1478280
1141338,3226,145107,116252,435.32,5,75,Y,8,NaN,NaN,...,0,13,102338.0,192,90135,N,1458,102,0,661087
1141339,6769,162168,93598,1.38,5,75,Y,8,NaN,NaN,...,0,29,234618.0,373,79246,N,5817,102,0,167073

In [14]:
test

,acqic,bacno,cano,conam,contp,csmcu,ecfg,etymd,flbmk,flg_3dsmk,...,iterm,locdt,loctm,mcc,mchno,ovrlt,scity,stocn,stscd,txkey
0,0,134508,45725,465.62,5,0,N,2,N,N,...,0,9,105114.0,451,0,N,5817,102,0,4376
1,0,78377,2295,465.62,5,0,N,2,N,N,...,0,6,104918.0,451,0,N,5817,102,0,2943
2,0,151054,197751,465.62,5,0,N,2,N,N,...,0,7,104917.0,451,0,N,5817,102,0,3387
3,6716,150887,4541,930.31,5,62,N,4,N,N,...,0,8,142028.0,329,37560,N,5820,102,0,1765957
4,6882,110356,133430,0.00,5,0,N,0,N,N,...,0,9,143657.0,459,2461,N,0,102,0,611269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380442,5588,95249,112041,1.38,5,75,Y,8,NaN,NaN,...,0,17,194234.0,296,73998,N,3426,42,0,668463
380443,6215,85771,169553,609.21,5,75,Y,2,NaN,NaN,...,0,14,133907.0,289,54828,N,3460,46,0,1846986
380444,6231,139728,168027,574.36,5,75,N,5,NaN,NaN,...,0,28,155437.0,245,18405,N,5817,102,0,992751
380445,6032,45406,197460,1.38,5,75,Y,2,NaN,NaN,...,0,24,215218.0,373,79246,N,5817,102,0,338215
380446,6716,48723,176440,406.59,5,75,N,5,NaN,NaN,...,0,13,163603.0,251,69607,N,2310,102,0,1055258

In [22]:
les = {}
ss = StandardScaler()
mms = MinMaxScaler()

def preprocessing_train(train_df):
    labels = train_df["fraud_ind"]
    df = train_df.drop(["fraud_ind", "txkey"], 1) # unique value
    df = df.fillna("NA") # only flbmk & flg3dmsk has full value
    
    for c in df.keys():
        if not (df[c].dtype == np.int64 or df[c].dtype == np.float64):
            le = LabelEncoder()
            df.loc[:,c] = le.fit_transform(df.loc[:,c])
            les.update({c:le})

    x = ss.fit_transform(df)
    x = mms.fit_transform(x)
    df = pd.DataFrame(x, index=df.index, columns=df.columns)    
    
    df["fraud_ind"] = labels
    
    return df

train_df = preprocessing_train(train)

In [21]:
train_df

,acqic,bacno,cano,conam,contp,csmcu,ecfg,etymd,flbmk,flg_3dsmk,...,iterm,locdt,loctm,mcc,mchno,ovrlt,scity,stocn,stscd,fraud_ind
0,0.999564,0.691103,0.178303,0.071274,0.833333,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.359551,0.731703,0.995643,0.574337,0.0,0.000000,0.953271,0.0,0
1,0.999564,0.094012,0.882785,0.071274,0.833333,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.056180,0.646121,0.995643,0.574337,0.0,0.000000,0.953271,0.0,0
2,0.975596,0.958965,0.140470,0.140955,0.833333,0.826667,0.0,0.5,0.0,0.0,...,0.0,0.044944,0.732949,0.538126,0.488215,0.0,0.491830,0.953271,0.0,0
3,0.867955,0.646705,0.381116,0.098999,0.833333,0.826667,0.0,0.4,0.0,0.0,...,0.0,0.056180,0.771867,0.572985,0.907731,0.0,0.871983,0.953271,0.0,0
4,0.931290,0.576228,0.230713,0.250596,0.500000,0.826667,0.0,0.4,0.0,0.0,...,0.0,0.056180,0.731585,0.738562,0.000000,0.0,0.879179,0.953271,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141335,0.876235,0.015310,0.253565,0.000191,0.833333,1.000000,1.0,0.2,0.5,0.5,...,0.0,0.325843,0.980827,0.540305,0.757906,0.0,0.871983,0.953271,0.0,0
1141336,0.261621,0.078294,0.643971,0.157869,0.833333,1.000000,1.0,0.8,0.5,0.5,...,0.0,0.000000,0.423841,0.437908,0.001917,0.0,0.277620,0.915888,0.0,0
1141337,0.918361,0.555317,0.071198,0.080233,0.833333,1.000000,1.0,0.8,0.5,0.5,...,0.0,0.033708,0.812183,0.455338,0.369985,0.0,0.871983,0.953271,0.0,0
1141338,0.468623,0.885424,0.544930,0.060388,0.833333,1.000000,1.0,0.8,0.5,0.5,...,0.0,0.134831,0.433711,0.418301,0.872497,0.0,0.218558,0.953271,0.0,0
1141339,0.983295,0.989529,0.438739,0.000191,0.833333,1.000000,1.0,0.8,0.5,0.5,...,0.0,0.314607,0.994317,0.812636,0.767092,0.0,0.871983,0.953271,0.0,0

In [23]:
def preprocessing_test(test_df):
    labels = test_df["fraud_ind"]
    df = test_df.drop(["fraud_ind", "txkey"], 1)
    df = df.fillna("NA")
    
    for c in df.keys():
        if not (df[c].dtype == np.int64 or df[c].dtype == np.float64):
            df.loc[:,c] = les[c].transform(df.loc[:,c])
    
    x = ss.transform(df)
    x = mms.transform(x)
    df = pd.DataFrame(x, index=df.index, columns=df.columns)
    
    df["fraud_ind"] = labels
    
    return df

test_df = preprocessing_train(test)

In [24]:
test_df

,acqic,bacno,cano,conam,contp,csmcu,ecfg,etymd,flbmk,flg_3dsmk,...,iterm,locdt,loctm,mcc,mchno,ovrlt,scity,stocn,stscd,fraud_ind
0,0.000000,0.820750,0.214335,0.064707,0.833333,0.000000,0.0,0.2,0.0,0.0,...,0.0,0.089888,0.445473,0.982571,0.000000,0.0,0.872506,0.953271,0.0,0
1,0.000000,0.478244,0.010758,0.064707,0.833333,0.000000,0.0,0.2,0.0,0.0,...,0.0,0.056180,0.444643,0.982571,0.000000,0.0,0.872506,0.953271,0.0,0
2,0.000000,0.921712,0.926955,0.064707,0.833333,0.000000,0.0,0.2,0.0,0.0,...,0.0,0.067416,0.444638,0.982571,0.000000,0.0,0.872506,0.953271,0.0,0
3,0.975596,0.920693,0.021286,0.129284,0.833333,0.826667,0.0,0.4,0.0,0.0,...,0.0,0.078652,0.601916,0.716776,0.363577,0.0,0.872956,0.953271,0.0,0
4,0.999709,0.673377,0.625451,0.000000,0.833333,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.089888,0.608820,1.000000,0.023822,0.0,0.000000,0.953271,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380442,0.811737,0.581195,0.525191,0.000192,0.833333,1.000000,1.0,0.8,0.5,0.5,...,0.0,0.179775,0.823168,0.644880,0.716292,0.0,0.513874,0.392523,0.0,0
380443,0.902818,0.523361,0.794777,0.084661,0.833333,1.000000,1.0,0.2,0.5,0.5,...,0.0,0.146067,0.567499,0.629630,0.530729,0.0,0.518974,0.429907,0.0,0
380444,0.905142,0.852602,0.787624,0.079818,0.833333,1.000000,0.0,0.5,0.5,0.5,...,0.0,0.303371,0.658744,0.533769,0.178158,0.0,0.872506,0.953271,0.0,0
380445,0.876235,0.277057,0.925591,0.000192,0.833333,1.000000,1.0,0.2,0.5,0.5,...,0.0,0.258427,0.912099,0.812636,0.767092,0.0,0.872506,0.953271,0.0,0
380446,0.975596,0.297297,0.827060,0.056503,0.833333,1.000000,0.0,0.5,0.5,0.5,...,0.0,0.134831,0.693352,0.546841,0.673788,0.0,0.346483,0.953271,0.0,0

In [28]:
train_df.to_csv("../data/type1_train.csv", index=False)

In [30]:
test_df.to_csv("../data/type1_test.csv", index=False)